spring:
  profiles:
    active:
    - dev

---
spring:
  profiles: dev     #开发环境
    application:
      name: zfx-cloud-config-dev
     
---
spring:
  profiles: test    #测试环境
    application:
      name: zfx-cloud-config-test 
      
#注意保存为UTF-8格式

